### ISSUE TITLE
How do you use UPM for you packages?

### ISSUE THREAD

**Issue by omid3098** [keijiro/Flipper#1]
Hi.
We are talking about your workflow using Unity package manager [here](https://github.com/omid3098/OpenPackageManagerRepository/issues/2)
I see that you have upm branch for some of your repositories and here in Package folder you define these packages as git submodules. so we have to sync these submodules using git and then they will appear in UPM as packages. and as they will sync locally in Packages folder, we have to repeat this workflow for each project.
So I want to know what is the point of doing this and how upm helps you here?
Am I missing something?

**Comment by keijiro** [comment]
According to the [Package Manage roadmap](https://www.youtube.com/watch?v=j4AAXS3HuMI), it's going to support Git URL in a future version. If it's implemented correctly, we don't have to use submodules any more -- they can be easily synced like the standard packages via the Package Manager UI. I'm using submodules as a workaround until this feature is implemented.

Please note that this is not the only way to deal with the situation. I don't recommend people using the same approach -- the git submodule feature is complicated and sometimes it can mess a project up. I'm using it just because I like to manage things in a modularized way.

**Comment by omid3098** [comment]
Thanks for clarifying.

**Comment by omid3098** [comment]
Thanks for clarifying.
